Managing user profile
smartbooster/authentication-bundle pull request #3
Opened 2018-04-06 14:13 UTC by mathieu-ducrot

**Issue** https://github.com/smartbooster/sandbox/issues/3

## Description

Add the user profile form and action.

2018-04-09 05:22 UTC, nicolas-bastien requested changes

2018-04-09 05:22 UTC, nicolas-bastien commented on src/Security/Form/Type/UserProfileType.php
> +    public function getName()
not needed : https://github.com/symfony/symfony-docs/issues/5588

2018-04-09 05:22 UTC, nicolas-bastien commented on src/Resources/translations/admin.fr.xlf
> +                <target>My compte</target>
Mon compte

2018-04-10 12:01 UTC, mathieu-ducrot commented on src/Security/Form/Type/UserProfileType.php
> +    public function getName()
i removed it on my last commit

2018-04-10 12:01 UTC, mathieu-ducrot commented on src/Resources/translations/admin.fr.xlf
> +                <target>My compte</target>
fixed it on the last commit

2018-04-10 12:20 UTC, merged